### ISSUE TITLE
TypeError @Conditions.py:344

### ISSUE THREAD

**Issue by Blyska** [Boyan-MILANOV/ropgenerator#10]
Hi Boyan,

First of all, thanks for the tool, keep up the good work ;)

Python throws a TypeError when trying to load a kernel executable.
Arch: x86, 32bits

Temporarily fixed the issue by adding a pair of None-checks @Condition.py:394.
Not sure if it's semantically reliable in any way though. 

Cheers,
Blyska

-----
### "Crashdump" ###

Logged from file x86translator.py, line 243
	%  |████████████                  | 042%Traceback (most recent call last):
[...]
  File "[...]/scripts/ROPGenerator", line 5, in <module>
    &nbsp;&nbsp;&nbsp;Main.main()
  File "[...]/Main.py", line 66, in main
    &nbsp;&nbsp;&nbsp;load(args[1:])
  File "[...]/Load.py", line 193, in load
    &nbsp;&nbsp;&nbsp;build(gadgetList)
  File "[...]/Database.py", line 553, in build
    &nbsp;&nbsp;&nbsp;gadget = Gadget([addr], raw)
  File "[...]/Gadget.py", line 75, in __init__
    &nbsp;&nbsp;&nbsp;self.semantics = self.graph.getSemantics()
  File "[...]/Graph.py", line 128, in getSemantics
    &nbsp;&nbsp;&nbsp;semantics.simplifyConditions()
  File "[...]/Semantics.py", line 239, in simplifyConditions
    &nbsp;&nbsp;&nbsp;if( p.cond.isTrue()):    
  File "[...]/Conditions.py", line 460, in isTrue
   &nbsp;&nbsp;&nbsp; res = self.customSimplify()
  File "[...]/Conditions.py", line 398, in customSimplify
    &nbsp;&nbsp;&nbsp;res = simplifyArrayEquality( leftArray, rightArray, self.cond)
  File "[...]/Conditions.py", line 344, in simplifyArrayEquality
    &nbsp;&nbsp;&nbsp;for i in range(0,len(a1)):
TypeError: object of type 'NoneType' has no len()

**Comment by Boyan-MILANOV** [comment]
Hey ! 

First of all thanks for the positive comments !

Your fix shouldn't affect the semantics too much. However it's only a workaround, and 'None' values shouldn't appear here. I'll check where it comes from and correct this. 
By the way don't spend so much time working on the master branch at the moment because I'm developing the v2.0 version in which all this semantic processing switches from python to C++ :)
