### ISSUE TITLE
[QoL] Add way to specify ROPgagdet parameters 

### ISSUE THREAD

**Issue by Blyska** [Boyan-MILANOV/ropgenerator#11]
Hi Boyan !

It'd be nice to be able to specify some ROPGadget arguments when using the "load" command.

For example, using a small 'depth' parameter can be useful when working on "big" binaries (looking at you, vmlinux...)

Cheers,
Blyska

**Comment by Boyan-MILANOV** [comment]
I added the **-r, --ropgadget_opts** option to the load command which lets you specify arguments to ROPgadget when loading a binary. 

I did it "quick and dirty" without checking what extra options where passed so it's up the user to make relevant choices. I'll certainly refine it in the v2.0 :)
