### ISSUE TITLE
ROPgadget: error: unrecognized arguments: 

### ISSUE THREAD

**Issue by Waterman178** [Boyan-MILANOV/ropgenerator#12]
![qq 20190225214928](https://user-images.githubusercontent.com/14991217/53341736-513e2800-3947-11e9-8a2a-35f0811d37b3.png)

ropgenerator  v1.3
ROPgadget 5.6
Debian OS

what happened????

**Comment by Boyan-MILANOV** [comment]
Arf, I apologize for the bug. 
This should be fixed now :)

**Comment by Waterman178** [comment]
> Arf, I apologize for the bug.
> This should be fixed now :)

You have not modified the branch of v1.3

**Comment by Boyan-MILANOV** [comment]
Other branches such as 'v1.3' usually contain work in progress and might not be stable. In fact the v1.3 branch has been abandoned for the 'cpp-version' one, which will soon replace 'master' when we'll release ROPGenerator **2.0**. 
So in short, use the 'master' branch instead ;)
