### ISSUE TITLE
Operand 'registers' is invalid or not yet supported

### ISSUE THREAD

**Issue by Waterman178** [Boyan-MILANOV/ropgenerator#13]
![default](https://user-images.githubusercontent.com/14991217/53687635-dc695480-3d71-11e9-8c3e-c7019b6b60a2.PNG)
what happened?

**Comment by Boyan-MILANOV** [comment]
Hey, 

ROPGenerator accepts semantic queries with registers and constants. "registers" isn't a valid register name so the query is invalid and the command returns an error... 
What behaviour did you expect ? 

Boyan

**Comment by Waterman178** [comment]
> Hey,
> 
> ROPGenerator accepts semantic queries with registers and constants. "registers" isn't a valid register name so the query is invalid and the command returns an error...
> What behaviour did you expect ?
> 
> Boyan

There is a structure address in [rsp+0x28]. There is a function address in this structure +0x30. I want to jump over.How can I find instructions that implement features like the following?

mov rax,[rsp+0x28]
jmp qword ptr[rax+0x30]

**Comment by Boyan-MILANOV** [comment]
There isn't yet a query type that implements double dereferencing.
I see 2 possible improvements to ROPGenerator that would fill this need: 

   1. enable nested expressions in queries like:  `find rip=mem( mem(rsp+0x28) + 0x30 )`
   2. enable a generic operand such as: `find  ?=mem(rsp+0x28) `

I'll mark this as a feature request, and implement those features in the 2.0 version :)
